// <auto-generated />
using System;
using EnterpriseStatistics.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseStatistics.Domain.Migrations
{
    [DbContext(typeof(EnterpriseStatisticsDbContext))]
    [Migration("20241113174332_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseStatistics.Domain.Models.Enterprise", b =>
                {
                    b.Property<ulong>("MainStateRegistrationNumber")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("main_state_registration_number");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int")
                        .HasColumnName("employee_count");

                    b.Property<string>("IndustryType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("industry_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OwnershipForm")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ownership_form");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int")
                        .HasColumnName("total_area");

                    b.HasKey("MainStateRegistrationNumber");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("EnterpriseStatistics.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("EnterpriseStatistics.Domain.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("Quanity")
                        .HasColumnType("int")
                        .HasColumnName("quanity");

                    b.Property<ulong>("enterprise_id")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("enterprise_id");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id");

                    b.HasIndex("enterprise_id");

                    b.HasIndex("supplier_id");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("EnterpriseStatistics.Domain.Models.Supply", b =>
                {
                    b.HasOne("EnterpriseStatistics.Domain.Models.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("enterprise_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseStatistics.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
