# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./EnterpriseStatistics/EnterpriseStatistics.sln
    - name: Copy test data files
      run: cp EnterpriseStatistics.Test/data.csv ./EnterpriseStatistics.Test/bin/Debug/net8.0/
    - name: Build
      run: dotnet build --no-restore ./EnterpriseStatistics/EnterpriseStatistics.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./EnterpriseStatistics/EnterpriseStatistics.sln
